00002390_DBSD_CW2/Controllers/ClientController.cs
using _00002390_DBSD_CW2.DAL;
using _00002390_DBSD_CW2.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _00002390_DBSD_CW2.Controllers
{
    public class ClientController : Controller
    {
        
        ////
        // GET: /Client/Details/5
        [Authorize]
        public ActionResult Details(string uname)
        {
            try
            {
                uname = this.User.Identity.Name;
                Client c = DbRepository.GetClientByUsername(uname);
                return View(c);
            }
            catch
            {
                return RedirectToAction("Login", "Account");
            }

        }

        ////
        //// GET: /Client/Create

        public ActionResult Registration()
        {
            return View();
        }

        //
        // POST: /Client/Create

        [HttpPost]
        public ActionResult Registration(Client c)
        {
            try
            {
                DbRepository.InsertClient(c);
                return RedirectToAction("Login", "Account");
            }
            catch (SqlException ex)
            {
                if (ex.Message.ToLower().Contains("clients_dob_ck"))
                {
                    ModelState.AddModelError("", "Invalid date of birth");
                    return View();
                }
                else
                {
                    ModelState.AddModelError("", "Phone is not in the rigth format! please follow this format +xxx-xx-xxx-xx-xx");
                    return View();
                }
            }
            catch
            {
                return View();
            }
        }

       
    }
}

00002390_DBSD_CW2/Controllers/ProductController.cs
using _00002390_DBSD_CW2.DAL;
using _00002390_DBSD_CW2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
namespace _00002390_DBSD_CW2.Controllers
{
    public class ProductController : Controller
    {
        //
        // GET: /Product/
        [Authorize]
        public ActionResult Index(string sortOrder, string currentFilter, string searchByType, string searchByTheme, string searchByTime, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.ThemeSortParm = String.IsNullOrEmpty(sortOrder) ? "theme_desc" : "";
            ViewBag.TypeSortParm = sortOrder == "Type" ? "type_desc" : "Type";
            ViewBag.WidthSortParm = sortOrder == "Width" ? "width_desc" : "Width";
            ViewBag.HeightSortParm = sortOrder == "Height" ? "height_desc" : "Height";
            ViewBag.QuantitySortParm = sortOrder == "Quantity" ? "quantity_desc" : "Quantity";
            ViewBag.TimeSortParm = sortOrder == "Time" ? "time_desc" : "Time";
            ViewBag.PriceSortParm = sortOrder == "Price" ? "price_desc" : "Price";
            if (searchByTheme != null)
            {

                page = 1;
            }
            else
            {
                searchByTheme = currentFilter;
            }
            ViewBag.CurrentFilter = searchByTheme;
            
            var products = from p in DbRepository.GetAllProducts() select p;

            ViewBag.TypeParam = searchByType;
            ViewBag.TimeParam = searchByTime;

            if (!string.IsNullOrEmpty(searchByTime))
            {
                products = products.Where(p => p.TimeToMake.ToString() == searchByTime); //|| p.PType.TypeOfProduct.ToUpper().StartsWith(searchString.ToUpper()) || p.Theme.ToUpper().StartsWith(searchString.ToUpper())).ToList();

            }
            if (!string.IsNullOrEmpty(searchByType))
            {
                products = products.Where(p => p.PType.TypeOfProduct.ToUpper().StartsWith(searchByType.ToUpper()));

            }
            if (!string.IsNullOrEmpty(searchByTheme))
            {
                products = products.Where(p => p.Theme.ToUpper().StartsWith(searchByTheme.ToUpper()));

            }
            
            
            //var pagedList = products.ToPagedList(pageNumber, _pageSize);
           //IPagedList<Product> productsToReturn = null;

            switch (sortOrder)
            {
                case "theme_desc":
                    products = products.OrderByDescending(p => p.Theme);
                    break;
                case "Type":
                    products = products.OrderBy(p => p.PType.TypeOfProduct);
                    break;
                case "type_desc":
                    products = products.OrderByDescending(p => p.PType.TypeOfProduct);
                    break;
                case "Width":
                    products = products.OrderBy(p => p.Width);
                    break;
                case "width_desc":
                    products = products.OrderByDescending(p => p.Width);
                    break;
                case "Height":
                    products= products.OrderBy(p => p.Height);
                    break;
                case "height_desc":
                    products = products.OrderByDescending(p => p.Height);
                    break;
                case "Quantity":
                    products = products.OrderBy(p => p.Quantity);
                    break;
                case "quantity_desc":
                    products= products.OrderByDescending(p => p.Quantity);
                    break;
                case "Time":
                    products = products.OrderBy(p => p.TimeToMake);
                    break;
                case "time_desc":
                    products = products.OrderByDescending(p => p.TimeToMake);
                    break;
                case "Price":
                    products = products.OrderBy(p => p.Price);
                    break;
                case "price_desc":
                    products = products.OrderByDescending(p => p.Price);
                    break;
                default:
                    products = products.OrderBy(p => p.Theme);
                    break;
            }
            int _pageSize = 20;
            int pageNumber = (page ?? 1);
            return View(products.ToPagedList(pageNumber, _pageSize));
        }
        



        //
        // GET: /Product/Order/5

        public ActionResult Order(int id)
        {
            Product p = DbRepository.GetProductById(id);
            Session["product"] = p;
            return RedirectToAction("Create", "Order");
        }
    }
}

00002390_DBSD_CW2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

    <!-- Date Picker css -->
     <link href="@Url.Content("~/Content/themes/base/jquery.ui.core.css")" 
        rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/jquery.ui.datepicker.css")" 
        rel="stylesheet"  type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/jquery.ui.theme.css")" 
        rel="stylesheet" type="text/css" /> 

    <link href="@Url.Content("~/Content/bootstrap.min.css")" 
        rel="stylesheet" type="text/css" /> 
    <link href="@Url.Content("~/Content/font-awesome.min.css")" 
        rel="stylesheet" type="text/css" /> 
    <link href="@Url.Content("~/Content/main.css")" 
        rel="stylesheet" type="text/css" /> 
    <link href="@Url.Content("~/Content/responsive.css")" 
        rel="stylesheet"  type="text/css" /> 
     <link href="@Url.Content("~/Content/prettyPhoto.css")" 
        rel="stylesheet"  type="text/css" /> 
     <link href="@Url.Content("~/Content/animate.min.css")" 
        rel="stylesheet"  type="text/css" /> 
    
</head>   
   
   <body class="homepage">

    <header id="header">

        <nav class="navbar navbar-inverse" role="banner">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
				
                <div class="collapse navbar-collapse navbar-right">
                    <ul class="nav navbar-nav">
                        <li ><a href="@Url.Action("LogOut", "Account")">Log out</a></li>
                        <li ><a href="@Url.Action("Index", "Product")">Products</a></li>
                        <li><a href="@Url.Action("Report", "Report")">Report</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account </a>
                            <ul class="dropdown-menu">
                                <li><a href="@Url.Action("ChangePassword", "ChangePassword")">Change Password</a></li>
                                <li><a href="@Url.Action("Details", "Client")">My Details</a></li>
                            </ul>
                        </li>                      
                    </ul>
                </div>
            </div><!--/.container-->
        </nav><!--/nav-->
		
    </header><!--/header-->

    <section id="feature" >
        <div class="container">
            @RenderBody()
        </div><!--/.container-->
    </section><!--/#feature-->

   
    <footer id="footer" class="midnight-blue">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    &copy; 2013 <a target="_blank" href="http://shapebootstrap.net/" title="Free Twitter Bootstrap WordPress Themes and HTML templates">ShapeBootstrap</a>. All Rights Reserved.
                </div>
                <div class="col-sm-6">
                    <ul class="pull-right">
                        <li><a href="#">Home</a></li>
                        <li><a href="#">About Us</a></li>
                        <li><a href="#">Faq</a></li>
                        <li><a href="#">Contact Us</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </footer><!--/#footer-->

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)

    <!-- for DatePicker -->
    @Scripts.Render("~/bundles/jqueryui") 
    <script>
        $(document).ready(function () {
            $('.datep').datepicker({ dateFormat: "yy-mm-dd" });
        });
   </script>   

</body>
</html>